### ISSUE TITLE
1.16.1 Crash when accessing advanced muffling block

### ISSUE THREAD

**Issue by freopt** [korti11/bettermuffling#15]
Was testing in creative and I opened the GUI of the advanced muffler. GUI opened but as soon as I click anything the game freezes and then crashes. Happened multiple times. Normal muffler seems to work fine. [Crash report](https://hastebin.com/zohejewozo.rb)

**Comment by korti11** [comment]
Thanks for the report.
Fixed in version 1.16.1-1.0.1.
