### ISSUE TITLE
Crash when changing tabs in Advanced Sound Muffler

### ISSUE THREAD

**Issue by Yawrf** [korti11/bettermuffling#17]
When I change tabs in the Advanced Sound Muffler GUI I get an Index Out Of Bounds exception, always index same as size

**Comment by Yawrf** [comment]
Also happens I change the range

**Comment by korti11** [comment]
Hey. First thanks for the report. Second, the crashlog as well as the version you are playing on would be nice if you could get me that :D

**Comment by Yawrf** [comment]
Here's the [crash report](https://pastebin.com/YfASxu9E) (playing on 1.16.5)

Also I later determined it was only happening (and always happening) when I had the listen for new sounds function enabled

**Comment by korti11** [comment]
The crash has been fixed in the version 1.0.3 and is now available on the CurseForge page. Thanks again for the report :D
