### ISSUE TITLE
Crash to desktop when enabling listening mode

### ISSUE THREAD

**Issue by Yawrf** [korti11/bettermuffling#18]
Hello, I'm back again, lol

Server updated to the latest version, as did I, client-side, and the same issue is back:

MC 1.16.5
[Crash Report](https://pastebin.com/6h5JZaiB)

**Comment by korti11** [comment]
I took another look at it. It crashed at the same point but because of a different cause 😂 
The new version on CurseForge and now it should crash anymore, at least at that point 😅
