### ISSUE TITLE
It doesn't muffle sounds

### ISSUE THREAD

**Issue by sepsol** [korti11/bettermuffling#3]
Minecraft 1.14.4
Forge 28.1.76
OptiFine HD U F4
Better Muffling-1.14.4-0.3.0-Beta

**Comment by korti11** [comment]
Could you maybe provide me the scenario where the sounds are not muffled, so I can try to repuduce it? So what sounds you tried to muffle, what muffle configuration you used, if it was in multiplayer or in singleplayer and if you did changes to the config file. That would be helpfuly. Thanks in advance.

**Comment by sepsol** [comment]
I had some trader llamas and cows next to me, I placed the block down and set friendly creatures to 100% and still heard their sounds. I tried again somewhere else and put a note block down next to it and this time set the jukebox/note block to 100% and it still didn't work. For final attempt I maxed out everything and I still could hear the cows, llamas, note blocks, ambient sounds, etc.

I used it in my test singleplayer world and I only set the HUD element to false in the config file. But before that the muffling didn't work either.

**Comment by sepsol** [comment]
It works fine, I'm an idiot :D
I should have turned everything off!

**Comment by sepsol** [comment]
No I still hear the cow sounds, maybe it is because I have [Better Animal Models ](https://www.curseforge.com/minecraft/mc-mods/better-animal-models)mod and it has its own sounds?!

**Comment by korti11** [comment]
Ok. I have to investigate in this why it's not working. Could be that it doesn't fire the sound event.

**Comment by sepsol** [comment]
Thanks

**Comment by korti11** [comment]
Fixed in version 0.4.0
