### ISSUE TITLE
Suggestion: a new tab in GUI for more control over game sounds

### ISSUE THREAD

**Issue by sepsol** [korti11/bettermuffling#4]
For example:

**REDSTONE BLOCKS**
- Pistons
- Droppers
- Dispensers
- Levers
- Pressure Plates
- Buttons
- Hooks with String

**FRIENDLY MOBS**
- cows
- chickens
- pigs
- sheeps
- parrots
- cats
- dogs
- etc...

**HOSTILE MOBS**
- zombies
- skeletons
- creepers
- spiders
- endermen
- zombie pigmen
- slimes
- phantoms
- etc...

**Comment by korti11** [comment]
I need to think about that. For something like this there was the mod Super Sound Muffler, there you could muffle specifice sounds, but only in a given range and at a given sound level and also as i can see at the time it seems that it doesn't get updated to 1.14, but about this I'm not 100% sure.

**Comment by sepsol** [comment]
It would be really useful, I don't want to install [Mute Pistons](https://www.curseforge.com/minecraft/mc-mods/mute-pistons) mod to entirely disable their sound, because without them it's sometimes hard to understand if a new redstone circute is working correctly or not. But sometimes when the work is done, it is useful if you could change their volume. I hope this makes its way to the game :)

**Comment by korti11** [comment]
Added in version 0.4.0
