### ISSUE TITLE
Compatibility: with AmbientSounds 3 mod

### ISSUE THREAD

**Issue by sepsol** [korti11/bettermuffling#6]
When I turn off Ambient/Environment sounds in [Better Muffling ](https://www.curseforge.com/minecraft/mc-mods/better-muffling)block, the [AmbientSounds 3](https://www.curseforge.com/minecraft/mc-mods/ambientsounds) sound effects don't change at all.

Minecraft 1.14.4
Forge 28.1.76

**Comment by korti11** [comment]
It could be that AmbientSounds 3 handles the sounds directly and doesn't fire the sound event. So I have to look if it is possible to muffle this sounds, without a hacke way.

**Comment by sepsol** [comment]
I reported it to them as well and it can be found [here](https://github.com/CreativeMD/AmbientSounds/issues/53).

**Comment by korti11** [comment]
As the mod dev says it here https://github.com/CreativeMD/AmbientSounds/issues/53#issuecomment-549284407 the sounds don't have positions so it's impossible for me to determine if a sound is in range of the muffling block or not.

**Comment by sepsol** [comment]
That's sad :(
I have to ditch that mod then.
