### ISSUE TITLE
Suggestion: being able to press middle mouse button to copy a muffling block with its settings while in creative

### ISSUE THREAD

**Issue by sepsol** [korti11/bettermuffling#7]
This is done in [Simple Trophies](https://www.curseforge.com/minecraft/mc-mods/simple-trophies) mod, so I think it's doable :)

**Comment by korti11** [comment]
Same here: https://github.com/korti11/bettermuffling/issues/5#issuecomment-549316448

**Comment by sepsol** [comment]
No, #5 is by crafting in survival, this is by middle-clicking in creative.

**Comment by korti11** [comment]
I was just referencing my comment not the whole issue.

**Comment by sepsol** [comment]
Oh, I see.

**Comment by korti11** [comment]
Added in version 0.4.0
